### PR TITLE
V1.5.0

### PR DESCRIPTION
**Pull request by etaletai13**

### CODE REVIEW

**Comment by etaletai13** [comment]
@Varunram please explain what you mean on the downstream PR. Unless it's the one from you that I merged into gmc earlier.

**Comment by Varunram** [comment]
Yes, that's the PR I was talking about

**Comment by Varunram** [comment]
`yarn` works but `yarn dist` doesn't because the script doesn't create `dist/musicoin*` before using this. Can you change that to `mkdir dist/` and then put in? Or I could do that

**Comment by Varunram** [comment]
Looks like it does work, my bad.

**Comment by Varunram** [comment]
Amazing job @etaletai13! It took long, but I think we finally made it in such a way that it works fine.

**Pull request merged**
