### PR TITLE
Fix #68 and #71

### LINKED ISSUE #68: Inform % of  blocks synced
On the first page, it would be nice to show a percentage of the blocks being synced, so that people wouldn't have to wait indefinitely. The way this would work is, on startup, get the tip block from orbiter, get the current block synced locally and continuously update the percentage. Accuracy to one decimal place is enough, but more are welcome anyway.

EDIT: The info is in the second page, so the first step is to move it to the first page, get rid of the loading bar on the first page, have a nice modal in a 123/12345 format with percentage in small letters at the bottom.

### PR DESCRIPTION
**Pull request by cryptofuture**
It fixes #68 and #71. More above it fixes critical enough bug, where currentBlock always was equal `0`
It also hides `msc-simple-login-view.html`

Overall  looks like that:
mscreenadv
Starting sync could be even faster, but this means that we need to start will larger memory cache, while 512 Mb is viable even for old computers or containers.

### CODE REVIEW

**Comment by Varunram** [comment]
Quick comments on the fix:
1. The percentage must be on the front page, replacing the current "Place Wait" and loading bars, so please shift that to the first page.
2.Regarding syncing, I'll put down a list of the expected fixes over at #71

**Comment by cryptofuture** [comment]
> The percentage must be on the front page, replacing the current "Place Wait" and loading bars, so please shift that to the first page.
Why we need to show `msc-simple-login-view.html` in the first place is very annoying and I bet everyone just click move me to the wallet? I think I can lock send button before sync complete, what you think about this?

**Comment by Varunram** [comment]
Yeah, I agree its a bit annoying, but people will complain that its not possible to send if we show them the second page directly. Hence the first page to warn them they can't send coins without properly syncing. Also, if possible, don't display the send icon on the second page if sync is not more than 98%.

**Comment by cryptofuture** [comment]
>  I think I can lock send button before sync complete, what you think about this?

> Yeah, I agree its a bit annoying, but people will complain that its not possible to send if we show them the second page directly. Hence the first page to warn them they can't send coins without properly syncing.
Locking send button should help without showing `msc-simple-login-view.html`
I could show alert or notification that person could not send before sync is complete, in case person clicked send button?

**Comment by Varunram** [comment]
> Locking send button should help without showing msc-simple-login-view.html
I could show alert or notification that person could not send before sync is complete, in case person clicked send button?

I would prefer we have the first page and automatically open the second page after the sync is complete. In case the person chooses to go ahead an open the second page anyway, let the sync button be locked and you can send a notification when the sync is complete. Nice idea regarding the notification!

**Comment by cryptofuture** [comment]
@immartian What you think `msc-simple-login-view.html`, could we hide it completely? I really don't want it to exist. More above with tutorial on start it will be 3 windows overall. First slide through tutorial, second click on open the wallet and only after this you in the wallet window.
It was easier to add show percent changes to the `msc-simple-login-view.html` from the start, but this one is so annoying, as bloody hell, so i decided to hide it.

**Comment by Varunram** [comment]
The tutorial is shown only on startup and would contain a password feature and backup option similar to mist. A user can create an account before syncing, its only that he cannot view the funds at his address. And yes, since it is easier to add it to the earlier page, we think it would be better to do it.  If the wallet has been synced, the user will not be required to click on "Open App". A one page wallet without any options on the nav bar is quite undesirable. If we are planning to have it as a single page wallet, we'd expect some functionality to be moved on to the nav bar, keeping only the critical info and options on the main screen.

**Comment by cryptofuture** [comment]
> If we are planning to have it as a single page wallet, we'd expect some functionality to be moved on to the nav bar

But `msc-simple-login-view.html` does not contain any useful functionality, beside bloody progress bar.
However I thought about it and could make ability to turn it off in the menu. But I'd prefer default without `msc-simple-login-view.html`

>If the wallet has been synced, the user will not be required to click on "Open App".

I highly doubt anyone runs wallet full-time after first sync, since geth/gmc is quite heavy on cpu. So it would be `msc-simple-login-view.html` on every launch.
> The tutorial is shown only on startup and would contain a password feature and backup option similar to mist. A user can create an account before syncing, its only that he cannot view the funds at his address. 

You should clarify about create account and backup in #65. There was nothing about it there.

**Comment by Varunram** [comment]
I'll update the info over at #65 regarding that. For now, if you're doing a single page wallet, we'd like some functionality to be moved to the nav bar. We have no problems if you could do that.

**Comment by Varunram** [comment]
Closed in favour of #77 which implements desired changes. @cryptofuture, I think the changes related to sync can be dealt with in #71

**Comment by cryptofuture** [comment]
I still working on it, turns out it takes more time, with pre xmas hassle. Beside I found out that we need per account backup. Current way with opening keystore is not too obvious. Also I think there is some error in the current peer used code (or gmc console displays only peers with active connection), so I just couldn't pull request local changes in the current state. Finished with menu and cache size changing.
Beside I doing it as the single page. More above I could say that #77 displays 0/0 after sync is done, and this is no good, basically because it just full my code copy but to the `msc-simple-login-view.html`.
And I also found error in last updated style.

**Comment by Varunram** [comment]
@cryptofuture No worries about bounty, it will be split according to code contribution:) You can continue to work on the issue and make updates, but we are going to stick with the two page design for now. I am reopening this so that we can combine both updates.

**Comment by Varunram** [comment]
Regarding the errors in the accepted PR, you could comment on that PR/fix it and bounty will be re-adjusted. Thanks.

**Comment by cryptofuture** [comment]
@Varunram 
I want to make rpcCall
I declared it as prototype in `web3-connector.js`
How I could access it from msc-profile-view scope.
Call is `admin.peers.forEach(function(value){console.log("enode://"+value.id+"@"+value.network.remoteAddress)})`
Could you give me example, pls.
What I discovered is that bootnodes file never really used and 14 default nodes build-in gmc always used on start.
addPeers function parse paste correctly, but loads 14 default nodes anyway.

**Comment by Varunram** [comment]
Sorry this got lost in between messages. bootnodes in gmc are the same as the ones we ship with every desktop wallet. rpccall wise, I don't know much about web3, so am afraid I can't help you out there.

**Comment by cryptofuture** [comment]
I got how it works, but promises are not too good to get data from json multiple arrays, so after killing day on it, I solved it much more easily with jason. Anyway all seems work, but since we have new changes, I trying to fix merge error, before pull request, and also I may need to backport that timer now. :( But overall all is ready, also more than day took just to test that sync and send lock feature.

**Pull request closed without merging**
