### PR TITLE
Adding spanish translation

### PR DESCRIPTION
**Pull request by AdrianMastronardi**

### CODE REVIEW

**Comment by cryptofuture** [comment]
Just attach files with translations, we would pull/commit it for you. Don't worry about reward, you will get it. Or just close this and:
Press fork on the GitHub.
Do `git clone -b release-1.5 https://github.com/AdrianMastronardi/desktop`
 Replace files with your changed files in cloned repository (or you can use [meld](http://meldmerge.org/))
Do `git add -A .` and after
`git commit  "Add Spanish translation"`and `git push origin`
After just open https://github.com/AdrianMastronardi/desktop and create pull request.

**Comment by AdrianMastronardi** [comment]
Here are the files. Thanks.
[spanish.zip](https://github.com/Musicoin/desktop/files/1741180/spanish.zip)

**Comment by wadalino** [comment]
In order the create the spanish version would be spanish es_ES and es_AR ... in spain there are a lot of words that we not use ... can i goes with es_ES ?

**Comment by cryptofuture** [comment]
@wadalino Adrian already finished Spanish translation. You can find it here: https://github.com/Musicoin/desktop/pull/182/files
https://github.com/Musicoin/desktop/pull/182
I done integration for him, since translators are not so good with git. If you find some errors in Adrian's translation, comment in the pull request with integration. We will close this one soon anyway.

**Pull request closed without merging**
