### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by etaletai13**
fixup build system and separate mods

### CODE REVIEW

**Comment by Varunram** [comment]
Clean install doesn't work:
```
yarn install v1.6.0
(node:5693) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ yarn clean
yarn run v1.6.0
(node:5694) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ (rm -rf interface/*) & (rm -f bin/gmc/*)
✨  Done in 0.12s.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "polymer-cli > polymer-build > @babel/plugin-transform-classes@7.0.0-beta.35" has incorrect peer dependency "@babel/core@7.0.0-beta.35".
[5/5] 📃  Building fresh packages...
[1/7] ⢀ gmc: (node:5707) [DEP0005] DeprecationWarning: Buffer() is depr
[-/7] ⢀ waiting...
[7/7] ⢀ wct-sauce: This will only happen once.
[-/7] ⢀ waiting...
error /Users/varunramg/Desktop/patch-1/node_modules/gmc: Command failed.
Exit code: 1
Command: yarn start
Arguments:
Directory: /Users/varunramg/Desktop/patch-1/node_modules/gmc
Output:
yarn run v1.6.0
(node:5707) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error An unexpected error occurred: "EISDIR: illegal operation on a directory, read".
info If you think this is a bug, please open a bug report with the information provided in "/Users/varunramg/Desktop/patch-1/node_modules/gmc/yarn-error.log".
```

**Comment by Varunram** [comment]
Note: I just ran `yarn` without anything else and I guess it should work?

**Comment by Varunram** [comment]
Lets track all `yarn` related changes here, please don't close and open more PRs which simply creates more confusion.

**Comment by cryptofuture** [comment]
I tested. And install with just `yarn`, would stuck if gmc failed to build and exited with with status 1.
Also Windows XP seem to support only node 4.8.7. But polymer cli wants version 8, this is why just changing engines line wouldn't help.

**Suggestions so far:**
- Remove gmc module as it highly likely to fail to build on all platforms and need specific go version.
- Remove nwbuilder, as it expects to copy gmc binary and build, and gmc module build will high likely fail.
- Avoid using polymer-cli.
- Don't use forked web3.js (try to pr to upstream instead)
I could ensure that interface module, while includes interface changes, and out of scope of just bower support pr, didn't had any bad or harm code, so if interface would be nice, its totally ok to just fork it.

**Comment by etaletai13** [comment]
I will use upstream gmc and web3. As soon as they incorporate fixes. Go >1.10 is most common, so it wins. The patch step can be skipped if you'd like - what you're asking is unnecessary. These things aren't hard coded, so explore the code a little before judging it unjustly.

**Comment by cryptofuture** [comment]
@etaletai13 I mean to have something like:
```
"scripts": {
"build:gmc" do something to install gmc module
```

**Comment by etaletai13** [comment]
closed in favor of #248

**Pull request closed without merging**
