### PR TITLE
Image compression and cleanups.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is untested since I haven't build the wallet. Please check each individual commit for the savings.

PS. there might be more unused files, but since I'm not familiar with the codebase, I'll leave this to someone else. :)

### CODE REVIEW

**Comment by Varunram** [comment]
Hey, thanks for the PR! The commit history is a bit messed up, with some files added and deleted. I'll fix that and merge. Thanks!

**Comment by XhmikosR** [comment]
Oh, I did that on purpose to keep separate changes, separately.

**Comment by Varunram** [comment]
@XhmikosR thanks! And *just* realised you were the same guy from bootstrap. Thanks for taking the time out to make a PR!

**Comment by XhmikosR** [comment]
Np :)

If you could sort the packaging issues along with the needed commits to the repo, it would be perfect.

I realized after I downloaded the new Windows build, that it includes 3 separate packages; you should split those to reduce the size of the archive. Also, try 7zip; it should improve things.

Last but not least, see if you can remove more files from the distribution, especially images. :)

**Comment by Varunram** [comment]
Ah, I'l try 7z, thanks! And yeah, there used to be lots of junk images, its a bit  better now, although I think they don't serve any purpose. Before removing though, I should test cross-platform (since they're icons)  so I think I'll do that along with release-1.0.

The packaging stuff wise, we're looking for a more permanent solution, which doesn't cause various problems like with the latest release, hopefully that can be solved and we can come up with fewer bugs :)

**Pull request merged**
