### PR TITLE
Chinese translation version-2

### PR DESCRIPTION
**Pull request by ooof**
@cryptofuture 
@Varunram
I am sorry, Not familiar with GitHub operations, I accidentally closed #188 .
However, I updated the translation, please let me know if you have any questions.

### CODE REVIEW

**Comment by Varunram** [comment]
Haha, sure no worries. We'l take it forward from here. Please reply with your musicoin address here so that we may credit the amount to you once the PR is merged. Thanks!

**Comment by cryptofuture** [comment]
Looks perfect now!

**Comment by ooof** [comment]
Thank you ！ :)
Can be sent here:   0xf18e990c4ba4b663eb5f2d00e306cec2bfa41d80

**Comment by Varunram** [comment]
Bounty sent!

**Pull request merged**
