### PR TITLE
Quick access to explorer

### PR DESCRIPTION
**Pull request by cryptofuture**
Might be considered as hacky way, but its a lot easier to implement, and it doesn't even needs user to be fully synced.

### CODE REVIEW

**Comment by Varunram** [comment]
An alternate way would be to change history to something like "Past tx history" so that the distinction between the two services is made clear.

**Comment by immartian** [comment]
Also I'm asking @seungjlee to set up a neater version of blockchain explorer. it's much faster than Orbiter now, and probably same to an API tunnel.

**Comment by cryptofuture** [comment]
@Varunram I actually don't know command to show last transaction or transactions using gmc, or what i should execute to shot transaction from nw.js. If you can suggest it, I could try implement it the right way.
I tried to search docs on gmc, but found nothing.
@immartian Current explorer is slow as hell. More above I have no idea, why you don't use cloudflare, it a shame not to use them, since even free plan is very good.

**Comment by immartian** [comment]
actually, it's not about cloudflare or not, the database scheme we used is not efficient enough, we need another way to redesign. It's why I'm checking if @seungjlee 's experiment can help.

**Comment by cryptofuture** [comment]
@immartian Actually even css loading is slow, loopls like static is from node directly. Page loading with just two post requests take 60-80 seconds under tor.

**Comment by immartian** [comment]
will dig into that and find a solution, hopefully soon.

**Comment by cryptofuture** [comment]
`Past tx history` is too long for column, and orbiter is confusing and is harder to find icon in the same style for it. I renamed to explorer.

**Comment by Varunram** [comment]
Thanks!

**Comment by immartian** [comment]
Just realized you should use API instead of loading a browser window:

https://github.com/Musicoin/orbiter/blob/8270661bfe057badc26967140d7b790dda47f069/routes/index.js

**Comment by immartian** [comment]
@cryptofuture  @seungjlee pls share the requirement of API for new explorer(currently at

**Comment by cryptofuture** [comment]
@immartian Nice this one works faster. I'll wait till it move to domain, hardcoding to ip, will be not cool.

**Comment by seungjlee** [comment]
@cryptofuture It's up and running now on https://explorer.musicoin.org. If you can specify the API that you need I can start working on it.

**Comment by cryptofuture** [comment]
@seungjlee Just take common api thats was already used for other explorers, give me link to it, and thats it. I think I'll be able to use it. 
offtop: Seems like new explorer runs on windows, have certificate issue time after time (at least when I try to use search) and its like you forgot to proxy it and remove node port.

**Comment by seungjlee** [comment]
I am pretty new with web server new development so any help with setting it up on a Windows server will be appreciated. My actual background is real time systems and high performance computing.

**Comment by cryptofuture** [comment]
@seungjlee I can't understand one thing, why its running on Windows in the first place? Or you running it locally right now, just for the test? It more much easy to run node with nginx under any Linux distro.
This is how I proxy another node application with nginx, for example:
```
server {
    listen  443 ssl http2;

    server_name host.example;
    ssl_certificate /etc/nginx/ssl/cert.crt;
    ssl_certificate_key /etc/nginx/ssl/key.key;

    error_log /var/log/nginx/example.log;
    access_log /var/log/nginx/example.log;

    location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

    proxy_pass http://10.x.x.x:3000/;

    }
}
```

**Comment by seungjlee** [comment]
Thanks, I have used nginx in Windows in the past but have never configured it. I started this little project on a local Windows machine and there has not been enough incentive for me to try a Linux machine.

**Comment by seungjlee** [comment]
https://explorer.musicoin.org should be working now. I just directly changed port from 3000 to 443 since I was only using 3000 since I could not get it to run on port 80. I was trying to redirect 80 to 443 with nginx without any luck. I tried the following config:

events {
  worker_connections 256;
}
http {
  server {
    listen 80;
    listen [::]:80;
    server_name explorer.musicoin.org;
    return 301 https://$host$request_uri;
  }
}

**Comment by cryptofuture** [comment]
Basically this how its done. Most time you need to terminate tls traffic on nginx, also if you need to proxy to https you just use https. But yes I think beside performance running node on 80 or 3000 is just the same on Windows, it would run with administrator privilege. 
How much space $M needs for blockchain now? I think I can up mirror to test how  fast your explorer could possibly work with proper static caching and under CDN.
```
server {
    listen  443 ssl http2;

    server_name  explorer.musicoin.org;
     # need different path on windows
    ssl_certificate /etc/nginx/ssl/cert.crt;
    ssl_certificate_key /etc/nginx/ssl/key.key;

    # need different path on windows
    error_log /var/log/nginx/explorer.log;
    access_log /var/log/nginx/explorer.log;

    location / {
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;

    proxy_pass http://127.0.0.1:3000/;

    }
}
```

**Comment by seungjlee** [comment]
The current blockchain takes about 33GB when you synchronize Parity in this mode to use their database for the block explorer. There was one painful detail about synchronizing Parity in this mode. You cannot use the --warp option so it does a very slow synchronization that takes excessive disk space if your hard drive is slow. I had no issues synchronizing on a local machine with an SSD but it was not easy on a VM in Google's cloud. There is an SSD option for the VM but looking at their specs I don't think it will help much. To be fair I am only using a free trial account on Google Cloud Platform so they might have better paid options.

Anyway, the synchronization was long and painful because Parity does multi-threaded accesses to the drive (reads and writes) which I usually do not recommend on most systems since it will just bottleneck with IO. Since the drive operations where not fast enough Parity will fill up the drive until it crashes during synchronization. Even 250 GB was not enough to keep up. So I had to restart Parity many many times to synchronize the blockchain. Thankfully, when you restart Parity, it cleans up the drive.

**Comment by cryptofuture** [comment]
@seungjlee Thats a lot I'll not be able to test it in own network properly without ordering extra resources.

**Comment by seungjlee** [comment]
Besides the redirecting http requests to https, is https://explorer.musicoin.org working for everyone now?

**Comment by Varunram** [comment]
@seungjlee If you'd like to get access to some of our servers, feel free to hit me up on Slack. The new explorer works fine too!

**Comment by seungjlee** [comment]
Oh, thanks, it will be good to try it from another machine. I actually just tried it from work and it seems to be fine.

**Comment by seungjlee** [comment]
@cryptofuture It looks like eventually I will have to take a look at using Linux servers considering the pricing of a Windows server vs. Linux in Google Cloud Platform.

**Comment by seungjlee** [comment]
Google stopped the new block explorer server claiming that it might be mining cryptocurrencies. That would be a very sad mining system for Musicoin.
I filed an appeal to this ridiculous claim.

**Comment by cryptofuture** [comment]
What else you can expect from evil corporation that could block your account anytime and never answer on support requests. I had personal story with them.
I could recommend OVH (vps or private cloud and not kimsufi will old hardware), or Vultr.
Scaleway has very cheap space, but most plans are sold, and rumors that they use not good enough cpu even on x86_64 plans. I didn't tried myself, so can't recommend. And don't use Digitalocean at any cost, they block accounts after you add new your own credit card pretty often, especially if use cards without your name on the card, like virtual card. My 5 cents.

**Comment by seungjlee** [comment]
https://explorer.musicoin.org is back up. The Google Police has set me free.

**Comment by cryptofuture** [comment]
I wonder why explorer didn't work in the tor browser. I have let's encrypt ca certificate in the browser certificate store, and all other let's encrypt websites work fine. Maybe the reason is incomplete chain? Did you include ca certificate on the button of the own certificate?

**Comment by seungjlee** [comment]
Mmm, I noticed also that older versions of Chrome were not working but it was fine after updating it.

**Pull request merged**
