### PR TITLE
adapts package.json for yarn; adds additional automation for build

### PR DESCRIPTION
**Pull request by etaletai13**
# Ready for review.

### CODE REVIEW

**Comment by etaletai13** [comment]
The added upshot of all of the yarn, for those of you who don't see the point in another npm client, is in simplicity. I am also removing the need for bower - which is no longer maintained - and enabling snyk and other systems to run at all needed places. Beyond that, there is no need to be building gmc manually and shoving it in like that! So that'll come this way also. A dev should end up only typing "yarn" and package with "yarn package". It'll make Everyone's life much simpler and code fixes less frequent.

**Comment by etaletai13** [comment]
screen shot 2018-04-02 at 2 10 42 pm
Things are coming along well.

**Comment by etaletai13** [comment]
It goes on to build the interface, and gmc, and the app. This is all still from the singular `yarn`.
screen shot 2018-04-02 at 2 13 16 pm

**Comment by etaletai13** [comment]
Do NOT merge this straight into master just yet. Unit tests, may as well do it now while shaking the boat anyway. Gotta make sure nothing broke; but it does look like a single-command to build the app will do.
screen shot 2018-04-02 at 2 16 33 pm

---

For what it's (kinda not) worth; it works for me. Which I'm only saying as a proof of at least the idea! I did not install or use Bower at any point, or anything else that isn't Yarn. Even the tools needed are installed only while needed.

**Comment by Varunram** [comment]
On first glance, PR looks great, please message here once you're done so that I can review extensively.

**Comment by etaletai13** [comment]
I'm dealing with getting yarn to understand what environment it's building for without user interaction. And that's going well; but I'll push that when it builds with only the already used commands to avoid a breaking change so that it's just 1.0.1. And while this is a lot of "work" I guess in a sense; it isn't. The bounty can be a token gesture and distributed to all of the contributors, if you wouldn't mind breaking from the usual ways! I mean that'll end up happening to any bounty anyway if it's paid my way. 👍  This patch with get a lot more contributors with less knowledge and more intuition, I think. And the knowledge pool here is doing just fine!

**Comment by Varunram** [comment]
Yeah sure, the bounty can be distributed to all those who have ideas and contribute to the PR :)

**Comment by etaletai13** [comment]
Things have changed a little bit, but it's all there. Give it a shot, it's kind of fun seeing it all go smoothly with one command. We can also see now that there are abandoned and deprecated packages we've been relying on, so bugs should be practically fixing themselves! I think this one is ready for merging. Migrating from Bower to yarn also will be a separate PR so there isn't time to distance the fork.

**Comment by cryptofuture** [comment]
Lets accept that to release-1.5 branch, so I could test it with actual builder, and do updates it if need.

**Comment by Varunram** [comment]
Works in theory, doesn't work in practice because of the huge bloat related to modules. Will revert unless suitable PR fixing this is available.

**Comment by etaletai13** [comment]
Working on it!

**Pull request merged**
