### PR TITLE
Add French translation.

### PR DESCRIPTION
**Pull request by ooof**
@clemsos  has translated the French, he gives me the document, I help him to send.
[musicoin-fr.json.zip](https://github.com/Musicoin/desktop/files/1754525/musicoin-fr.json.zip)

Thank you very much!
Please let me know if you have any questions.

### CODE REVIEW

**Comment by clemsos** [comment]
Great! You're welcome

**Comment by clemsos** [comment]
Ok great let me know if there is any morr changes to be made

**Comment by cryptofuture** [comment]
Phrases we also need:
```
    "profileViewHtml_Btn_LOCATION": "SELECT LOCATION",
    "profileViewHtml_datadir": "Please select new location to move gmc directory with blockchain data",
    "profileViewHtml_datadir_warning1": "Please wait for the alert with instructions after you selected new location",
    "profileViewHtml_datadir_warning2": "Sometimes operation could take up to 1 hour, it depends from blockchain size and read/write speed",
    "profileViewHtml_datadir_alert1": "Blockchain data successfully moved in ",
    "profileViewHtml_datadir_alert2": "You can restart your wallet now",
    "profileViewHtml_es_es": "Spanish (Spain)",
    "profileViewHtml_es_ar": "Spanish (Argentina)",
    "profileViewHtml_wipeBlockChain": "Here you can wipe blockchain data: press <OK> to continue",
    "profileViewHtml_wipeBlockChain_warning1": "This action will remove all blockchain data",
    "profileViewHtml_wipeBlockChain_warning2": "Please wait for the alert with instructions after you pressed <Confirm>",
    "profileViewHtml_wipeBlockChain_finished": "Blockchain data successfully removed",
    "profileJS_menu_Lang_Es": "Change language: Spanish",
    "profileJS_menu_DataDir": "Move blockchain data",
    "profileJS_menu_logDir": "Open logs directory",
    "profileJS_menu_removeGmcFolder": "Wipe blockchain data",
```
Merged file fr + eng 
[musicoin-fr.json.zip](https://github.com/Musicoin/desktop/files/1762677/musicoin-fr.json.zip)

**Comment by Varunram** [comment]
@clemsos Could you translate the strings attached above too? Thanks!

**Comment by Varunram** [comment]
@clesmos Any updates? Also, we need your account address in order for us to be able to send the bounty to you.

**Comment by clemsos** [comment]
Hey sorry for the delay I was busy with other things. Will try to finalize the missing part very soon

**Comment by clemsos** [comment]
Hi !

Finally, here is the rest of the translation :

```
"profileViewHtml_Btn_LOCATION": "CHOISIR L'EMPLACEMENT",
"profileViewHtml_datadir": "Choisissez  un nouvel emplacement pour déplacer
le répertoire gmc contenant les données de blockchain",
"profileViewHtml_datadir_warning1": "Attendez la notification contenant les
instructions après avoir sélectionné votre emplacement",
"profileViewHtml_datadir_warning2": "Parfois, les opérations peuvent
prendre jusqu'à une heure, selon la taille de la blockchain et la vitesse
de lecture/écriture",
"profileViewHtml_datadir_alert1": "Les données de blockchain ont été
déplacés correctement",
"profileViewHtml_datadir_alert2": "Vous pouvez maintenant redémarrer votre
wallet",
"profileViewHtml_es_es": "Espagnol (Espagne)",
"profileViewHtml_es_ar": "Espagnol (Argentine)",
"profileViewHtml_wipeBlockChain": "ICI vous pouvez supprimer les données de
blockchain : appuyer sur <OK> pour continuer",
"profileViewHtml_wipeBlockChain_warning1": "Cette action supprimera toutes
les données de blockchain",
"profileViewHtml_wipeBlockChain_warning2": "Attendez la notification avec
les instructions après avoir pressé <Confirm>",
"profileViewHtml_wipeBlockChain_finished": "Les données de blockchain ont
été supprimées correctement",
"profileJS_menu_Lang_Es": "Changer de langage: Espagnol",
"profileJS_menu_DataDir": "Déplacer les données de blockchain",
"profileJS_menu_logDir": "Ouvrir le répertoire de logs",
"profileJS_menu_removeGmcFolder": "Supprimer les données de blockchain",
```

Also my wallet address
MUSIC14047e44f21995530e459c

**Comment by Varunram** [comment]
Carried over to #202. Bounty will be credited i the next three days. Thanks!

**Comment by cryptofuture** [comment]
@clemsos  `MUSIC14047e44f21995530e459c`
This is looks more like email verification code, don't ever try to send funds on that!
We need valid wallet account address.

**Comment by Varunram** [comment]
Can confirm that this is indeed a verification code and not an address. @clemsos we need your wallet address (can be found in the profile section of your wallet at https://musicoin.org/nav/profile).

**Comment by clemsos** [comment]
haha sorry ! Copy/paste mistake

Here is the actual address

0x010502198d279990e28b4768572ad9858eba1816

Thanks !

**Pull request closed without merging**
